// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zkswcwwjnsrvpqxnqdbm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inprc3djd3dqbnNydnBxeG5xZGJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MDI5OTcsImV4cCI6MjA2NTk3ODk5N30.qMPlpBz79xMiRJFo3SFs6L0bm7hA9ggRuUmWeDoea_g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);