// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xgnoznhtxyymdubplecs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhnbm96bmh0eHl5bWR1YnBsZWNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NDgxNDEsImV4cCI6MjA2NjUyNDE0MX0.O1dSBfb1aT7MsPMA_-NMeic5kOOk_3q2WsiFDhTXd7A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);